#Build stage
FROM maven:3.8.7-openjdk-18 as build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

#Runtime stage
FROM amazoncorretto:17
WORKDIR /app
COPY --from=build /build/target/payment-service-1.0.0.jar /app/

EXPOSE 8084

ARG APP_VERSION=1.0.0
ARG PROFILE=default

ENV JAR_VERSION=${APP_VERSION}
ENV ACTIVE_PROFILE=${PROFILE}

CMD java -jar -DSpring.profiles.active=${ACTIVE_PROFILE} payment-service-${JAR_VERSION}.jar
